// MyPriceFinder/build.gradle.kts (프로젝트 최상위)
// DO NOT EDIT THIS FILE! It is regenerated during project creation.
plugins {
    // Hilt 플러그인을 적용하려면 버전을 명시하고 apply false를 추가해야 합니다.
    id("com.google.dagger.hilt.android") version "2.48" apply false
    id("com.android.application") version "8.2.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.22" apply false
}